<?php
    session_start();
    require_once('../Models/medicineVerificationModel.php');
    require_once('../Models/counterfeitModel.php');
    
    if(!isset($_SESSION['user_id'])){
        header('location: ../Views/login.php');
        exit();
    }
    
    if(!isset($_SESSION['user_type']) || $_SESSION['user_type'] != 'admin'){
        header('location: ../Views/verify_medicine.php');
        exit();
    }
    
    // Get statistics
    $verificationStats = getOverallVerificationStats();
    $todayCount = getTodayVerificationCount();
    $counterfeitStats = getCounterfeitStats();
    $recentVerifications = getRecentVerifications(10);
    $recentCounterfeits = getRecentCounterfeitReports(10);
    
    // Calculate percentages
    $totalVerifications = $verificationStats['total_verifications'];
    $genuineCount = $verificationStats['genuine_count'];
    $genuinePercentage = $totalVerifications > 0 ? round(($genuineCount / $totalVerifications) * 100, 1) : 0;
    
    // Set headers for HTML download that can be printed/saved as PDF
    header('Content-Type: text/html; charset=utf-8');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>MedVerify Summary Report - <?php echo date('Y-m-d'); ?></title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 12pt;
        }
        .header {
            text-align: center;
            border-bottom: 3px solid #4CAF50;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #4CAF50;
            margin: 0;
        }
        .metadata {
            text-align: right;
            color: #666;
            margin-bottom: 30px;
        }
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 30px;
        }
        .stat-box {
            display: table-cell;
            width: 25%;
            padding: 20px;
            text-align: center;
            border: 2px solid #ddd;
            margin: 5px;
        }
        .stat-box h3 {
            margin: 0 0 10px 0;
            font-size: 14pt;
        }
        .stat-box .number {
            font-size: 32pt;
            font-weight: bold;
            margin: 10px 0;
        }
        .stat-box.green .number { color: #4CAF50; }
        .stat-box.blue .number { color: #2196F3; }
        .stat-box.orange .number { color: #FF9800; }
        .stat-box.red .number { color: #f44336; }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }
        table, th, td {
            border: 1px solid #000;
        }
        th {
            background-color: #4CAF50;
            color: white;
            padding: 12px;
            text-align: left;
        }
        td {
            padding: 10px;
        }
        .section-title {
            background-color: #f0f0f0;
            padding: 15px;
            margin: 30px 0 15px 0;
            font-size: 16pt;
            font-weight: bold;
            border-left: 5px solid #4CAF50;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            color: #666;
            font-size: 10pt;
            border-top: 2px solid #ddd;
            padding-top: 20px;
        }
        @media print {
            button { display: none; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🏥 MedVerify</h1>
        <h2>Medicine Verification & Authentication System</h2>
        <h3>Summary Report</h3>
    </div>

    <div class="metadata">
        <strong>Report Generated:</strong> <?php echo date('F d, Y h:i A'); ?><br>
        <strong>Generated By:</strong> <?php echo $_SESSION['full_name']; ?> (Admin)<br>
        <strong>Report Type:</strong> Comprehensive Summary
    </div>

    <div style="text-align: center; margin-bottom: 20px;">
        <button onclick="window.print()" style="background-color: #4CAF50; color: white; padding: 15px 30px; font-size: 14pt; border: none; cursor: pointer; border-radius: 5px;">
            🖨️ Print / Save as PDF
        </button>
    </div>

    <div class="section-title">📊 Medicine Verification Statistics</div>

    <div class="stats-grid">
        <div class="stat-box blue">
            <h3>Today's Verifications</h3>
            <div class="number"><?php echo $todayCount; ?></div>
            <p>Scanned Today</p>
        </div>
        <div class="stat-box green">
            <h3>Genuine Medicines</h3>
            <div class="number"><?php echo $genuineCount; ?></div>
            <p><?php echo $genuinePercentage; ?>% Authentic</p>
        </div>
        <div class="stat-box orange">
            <h3>Suspicious</h3>
            <div class="number"><?php echo $verificationStats['suspicious_count']; ?></div>
            <p>Flagged</p>
        </div>
        <div class="stat-box red">
            <h3>Counterfeit</h3>
            <div class="number"><?php echo $verificationStats['counterfeit_count']; ?></div>
            <p>Detected</p>
        </div>
    </div>

    <div class="section-title">🚨 Counterfeit Report Statistics</div>

    <div class="stats-grid">
        <div class="stat-box blue">
            <h3>Total Reports</h3>
            <div class="number"><?php echo $counterfeitStats['total_reports']; ?></div>
            <p>All Time</p>
        </div>
        <div class="stat-box orange">
            <h3>Pending Review</h3>
            <div class="number"><?php echo $counterfeitStats['pending_reports']; ?></div>
            <p>Awaiting Action</p>
        </div>
        <div class="stat-box red">
            <h3>Verified</h3>
            <div class="number"><?php echo $counterfeitStats['verified_reports']; ?></div>
            <p>Confirmed Fake</p>
        </div>
        <div class="stat-box green">
            <h3>Rejected</h3>
            <div class="number"><?php echo $counterfeitStats['rejected_reports']; ?></div>
            <p>Not Counterfeit</p>
        </div>
    </div>

    <div class="section-title">📋 Recent Verifications (Last 10)</div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>User</th>
                <th>Medicine</th>
                <th>Barcode</th>
                <th>Result</th>
                <th>Confidence</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($recentVerifications as $verify){ ?>
            <tr>
                <td><?php echo date('M d, Y H:i', strtotime($verify['verified_at'])); ?></td>
                <td><?php echo $verify['username']; ?></td>
                <td><?php echo $verify['medicine_name'] ? $verify['medicine_name'] : 'Unknown'; ?></td>
                <td><?php echo $verify['barcode_scanned']; ?></td>
                <td style="color: <?php echo ($verify['verification_result'] == 'Genuine') ? 'green' : (($verify['verification_result'] == 'Counterfeit') ? 'red' : 'orange'); ?>; font-weight: bold;">
                    <?php echo $verify['verification_result']; ?>
                </td>
                <td><?php echo $verify['confidence_score']; ?>%</td>
            </tr>
            <?php } ?>
        </tbody>
    </table>

    <div class="section-title">🚨 Recent Counterfeit Reports (Last 10)</div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Reported By</th>
                <th>Medicine</th>
                <th>Barcode</th>
                <th>Location</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            if(count($recentCounterfeits) > 0){
                foreach($recentCounterfeits as $report){ 
            ?>
            <tr>
                <td><?php echo date('M d, Y', strtotime($report['reported_date'])); ?></td>
                <td><?php echo $report['username']; ?></td>
                <td><?php echo $report['medicine_name'] ? $report['medicine_name'] : 'Unknown'; ?></td>
                <td><?php echo $report['barcode_scanned']; ?></td>
                <td><?php echo $report['purchase_location']; ?></td>
                <td style="color: <?php echo ($report['status'] == 'Verified') ? 'red' : (($report['status'] == 'Pending') ? 'orange' : 'gray'); ?>; font-weight: bold;">
                    <?php echo $report['status']; ?>
                </td>
            </tr>
            <?php 
                }
            }else{ 
            ?>
            <tr>
                <td colspan="6" style="text-align: center;">No counterfeit reports yet</td>
            </tr>
            <?php } ?>
        </tbody>
    </table>

    <div class="footer">
        <p><strong>MedVerify - Medicine Authentication & Verification System</strong></p>
        <p>Protecting Public Health Through Technology</p>
        <p>&copy; 2025 MedVerify. All Rights Reserved.</p>
        <p style="font-size: 8pt; margin-top: 20px;">This is an official report generated from the MedVerify system. Data is current as of <?php echo date('F d, Y h:i A'); ?>.</p>
    </div>
</body>
</html>
